bundler_args: "--without development production"
language: ruby
rvm:
  - 2.0.0
branches:
  only:
    - master
before_install: gem install bundler --pre
before_script:
  - cp config/database.yml.example config/database.yml
  - cp config/application.yml.example config/application.yml
  - rake db:migrate